### ISSUE TITLE
Should `list_tags` return a set?

### ISSUE THREAD

**Issue by pastewka** [jic-dtool/dtool-lookup-webapp#6]
Currently `list_tags` returns a list. The AzureStorageBroker tests test for an explicit order of the tags.

My question:
* Should the tags be returned in some specific order, e.g. the order in which they are created?
* If not, should `list_tags` return a `set`?

**Comment by tjelvar-olsson** [comment]
Sorry, this question dropped off my radar.

I don't think there is any specific requirement for a specific order. If there was I think it should be alphabetical order. I'm not keen on using sets because because they are quite python specific, for example I don't think they can be represented using JSON.

Do you have a specific use case where there order of the tags would be important or where the use of sets would be preferred?

**Comment by pastewka** [comment]
I don't think it matters. There was a case (in the tests for the SMB storage broker) where different orders were returned, I turned this into a set in the test which works perfectly fine. I have no strong feeling about this.

**Comment by tjelvar-olsson** [comment]
Since JSON does not support "sets" I'm closing this issue
